version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=95529b41a5f447abe23fa9b7cd3f01a5
      - NEXT_PUBLIC_APP_NAME=LocalSafe.eth
      - NEXT_PUBLIC_APP_DESCRIPTION=Local Safe Wallet Interface
    restart: unless-stopped
